image: ocaml/opam:ubuntu

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: opam init && opam install dune core core_bench utop ocaml-lsp-server ocamlformat ppx_jane ppx_let
    # Watch for compilation errors as we go along.
    command: eval $(opam env) && dune build @runtest -w --auto-promote

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#  - port: 3000
#    onOpen: open-preview
