image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo "Init!"
    # Watch for compilation errors as we go along.
    command: eval $(opam env) && dune build @runtest -w
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#  - port: 3000
#    onOpen: open-preview
